# Generated by Django 4.2.9 on 2024-03-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocProdIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_prod_in_num', models.CharField(max_length=50)),
                ('doc_prod_in_date', models.DateField()),
                ('raw_sum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_sum', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='DocProdOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_prod_out_num', models.CharField(max_length=50)),
                ('doc_prod_out_date', models.DateField()),
                ('doc_prod_out_sum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DocRawIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_raw_in_num', models.CharField(max_length=50)),
                ('doc_raw_in_date', models.DateField()),
                ('doc_raw_in_sum', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_num', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='ProductWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_prod_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_address', models.CharField(max_length=200)),
                ('supplier_phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.product')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.raw')),
            ],
        ),
        migrations.CreateModel(
            name='RawRest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_rest', models.DecimalField(decimal_places=6, max_digits=18)),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.raw')),
                ('warehouse_raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.rawwarehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_rest', models.DecimalField(decimal_places=6, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.product')),
                ('warehouse_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.productwarehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DocRawInT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_raw_in_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('doc_raw_in_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('doc_raw_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.docrawin')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.raw')),
            ],
        ),
        migrations.AddField(
            model_name='docrawin',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.supplier'),
        ),
        migrations.CreateModel(
            name='DocProdOutT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_prod_out_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('doc_prod_out_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('doc_prod_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.docprodout')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='DocProdInT2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('doc_prod_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.docprodin')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.raw')),
            ],
        ),
        migrations.CreateModel(
            name='DocProdInT1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('doc_prod_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.docprodin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='docprodin',
            name='warehouse_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.productwarehouse'),
        ),
        migrations.AddField(
            model_name='docprodin',
            name='warehouse_raw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.rawwarehouse'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('product', 'raw'), name='unique_Recipe'),
        ),
        migrations.AddConstraint(
            model_name='rawrest',
            constraint=models.UniqueConstraint(fields=('raw', 'warehouse_raw'), name='unique_RawRest'),
        ),
        migrations.AddConstraint(
            model_name='productrest',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse_prod'), name='unique_ProductRest'),
        ),
        migrations.AddConstraint(
            model_name='docrawint',
            constraint=models.UniqueConstraint(fields=('doc_raw_in', 'raw'), name='unique_RawInT'),
        ),
        migrations.AddConstraint(
            model_name='docprodoutt',
            constraint=models.UniqueConstraint(fields=('doc_prod_out', 'product'), name='unique_ProdOutT'),
        ),
        migrations.AddConstraint(
            model_name='docprodint2',
            constraint=models.UniqueConstraint(fields=('doc_prod_in', 'raw'), name='unique_ProdInT2'),
        ),
        migrations.AddConstraint(
            model_name='docprodint1',
            constraint=models.UniqueConstraint(fields=('doc_prod_in', 'product'), name='unique_ProdInT1'),
        ),
    ]
