# Generated by Django 4.2.9 on 2024-03-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_customer_docprodin_docprodout_docrawin_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docprodin',
            name='product_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='docprodin',
            name='raw_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='docprodout',
            name='doc_prod_out_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='docrawin',
            name='doc_raw_in_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
