# Generated by Django 4.2.9 on 2024-03-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_alter_docprodin_product_sum_alter_docprodin_raw_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrest',
            name='product_rest',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='rawrest',
            name='raw_rest',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
