# Generated by Django 4.2.9 on 2024-03-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_alter_productrest_product_rest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
