# Generated by Django 4.2.9 on 2024-04-06 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_alter_docrawin_doc_raw_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docrawin',
            name='raw_warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store_app.rawwarehouse', verbose_name='Склад'),
        ),
    ]
