# Generated by Django 4.2.9 on 2024-04-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_alter_docrawin_doc_raw_in_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrawin',
            name='doc_raw_in_num',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер документа'),
        ),
    ]
