# Generated by Django 4.2.9 on 2024-04-06 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_alter_docrawin_doc_raw_in_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='docprodout',
            name='prod_warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store_app.productwarehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='docprodout',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.customer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='docprodout',
            name='doc_prod_out_date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='docprodout',
            name='doc_prod_out_num',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='docprodout',
            name='doc_prod_out_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='docprodoutt',
            name='doc_prod_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.docprodout', verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='docprodoutt',
            name='doc_prod_out_cost',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена ГП'),
        ),
        migrations.AlterField(
            model_name='docprodoutt',
            name='doc_prod_out_quantity',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Количество ГП'),
        ),
        migrations.AlterField(
            model_name='docprodoutt',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.product', verbose_name='Готовая продукция'),
        ),
    ]
