# Generated by Django 4.2.9 on 2024-04-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_alter_docprodin_doc_prod_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docprodint1',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена ГП'),
        ),
        migrations.AddField(
            model_name='docprodint2',
            name='raw_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена сырья'),
        ),
        migrations.AlterField(
            model_name='docprodin',
            name='warehouse_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.productwarehouse', verbose_name='Склад готовой продукции'),
        ),
    ]
