# Generated by Django 4.2.9 on 2024-04-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_docprodint1_product_cost_docprodint2_raw_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docprodint1',
            name='product_quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Количество ГП'),
        ),
        migrations.AlterField(
            model_name='docprodint2',
            name='raw_quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Количество сырья'),
        ),
    ]
