# Generated by Django 4.2.9 on 2024-05-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_alter_docprodint1_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw',
            name='raw_num',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
