# Generated by Django 4.2.9 on 2024-05-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_alter_raw_raw_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_num',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
